name: Build and Convert Filters

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pip dependencie
        run: pip install requests

      - name: Install sing-box
        run: curl -fsSL https://sing-box.app/install.sh | sh -s -- --beta

      - name: Run merge rules script
        run: python run.py

      - name: Convert rules to srs
        run: sing-box rule-set convert --type adguard merged_rules.txt --output geosite-dnsblock.srs

      - name: Commit and push srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add geosite-dnsblock.srs
          git commit -m "Update geosite-dnsblock.srs" || echo "No changes"
          git push